"""
Multi-Agent RAG API  —  Deploy on Koyeb
Start command: uvicorn main:app --host 0.0.0.0 --port $PORT

Environment variable required:
  GEMINI_API_KEY=<your key>

Required files in same directory:
  gemini_dogdb.json   (generated by reembed.py — NOT the original dogdb.json)

Agents
  1. Guard    — checks the question is appropriate and dog-related
  2. Grader   — decides whether the vector DB context answers the question
  3. Answerer — generates the final friendly response (from DB or web search)
"""

import json
import os
from contextlib import asynccontextmanager

import numpy as np
import google.generativeai as genai
from duckduckgo_search import DDGS
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ── shared state ──────────────────────────────────────────────────────────────
_state: dict = {}

EMBED_MODEL = "models/text-embedding-004"
GEN_MODEL   = "gemini-1.5-flash"


@asynccontextmanager
async def lifespan(app: FastAPI):
    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY environment variable is not set.")
    genai.configure(api_key=api_key)

    _state["llm"] = genai.GenerativeModel(GEN_MODEL)

    with open("gemini_dogdb.json") as f:
        db = json.load(f)

    _state["docs"]       = db["documents"]
    _state["metadatas"]  = db["metadatas"]
    _state["embeddings"] = np.array(db["embeddings"], dtype=np.float32)

    # Pre-normalise stored embeddings once for fast cosine search
    norms = np.linalg.norm(_state["embeddings"], axis=1, keepdims=True)
    _state["embeddings_norm"] = _state["embeddings"] / np.clip(norms, 1e-10, None)

    print(f"✅  RAG ready — {len(_state['docs'])} documents indexed")
    yield
    _state.clear()


# ── app ───────────────────────────────────────────────────────────────────────
app = FastAPI(title="Dog RAG API", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten to your Cloudflare Pages URL in production
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ── helpers ───────────────────────────────────────────────────────────────────
def embed_query(text: str) -> np.ndarray:
    result = genai.embed_content(
        model=EMBED_MODEL,
        content=text,
        task_type="retrieval_query",
    )
    vec = np.array(result["embedding"], dtype=np.float32)
    return vec / np.linalg.norm(vec)


def vector_search(query: str, n: int = 3) -> list[str]:
    q_vec = embed_query(query)
    scores = _state["embeddings_norm"] @ q_vec
    top_idx = np.argsort(scores)[-n:][::-1]
    return [_state["docs"][i] for i in top_idx]


def ask_gemini(prompt: str) -> str:
    return _state["llm"].generate_content(prompt).text.strip()


def yes_no(prompt: str) -> bool:
    return ask_gemini(prompt).upper().startswith("Y")


def duckduckgo_search(query: str, max_results: int = 3) -> str:
    try:
        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=max_results))
        return "\n\n".join(r["body"] for r in results)
    except Exception as exc:
        print(f"DuckDuckGo search failed: {exc}")
        return ""


# ── schema ────────────────────────────────────────────────────────────────────
class QueryRequest(BaseModel):
    dog_breed: str
    question: str


# ── endpoint ─────────────────────────────────────────────────────────────────
@app.get("/health")
async def health():
    return {"status": "ok"}


@app.post("/ask/")
async def ask(req: QueryRequest):
    breed    = req.dog_breed.strip()
    question = req.question.strip()

    if not breed or not question:
        raise HTTPException(status_code=422, detail="breed and question are required.")

    # ── Agent 1: Guard ────────────────────────────────────────────────────────
    guard_ok = yes_no(
        f'A user selected the dog breed "{breed}" and asked: "{question}"\n\n'
        "Is this question (1) appropriate / not harmful AND (2) related to dogs or dog care?\n"
        'Answer ONLY "YES" or "NO".'
    )
    if not guard_ok:
        return {
            "response": (
                "I can only answer appropriate questions about dog breeds. "
                "Feel free to ask me anything about your pup! 🐾"
            )
        }

    # ── Agent 2: Retrieval grader ─────────────────────────────────────────────
    context_docs = vector_search(f"{breed}: {question}", n=3)
    context      = "\n\n".join(context_docs)

    use_db = yes_no(
        f"Dog breed: {breed}\nQuestion: {question}\n\n"
        f"Retrieved context from knowledge base:\n{context}\n\n"
        f"Does this context adequately and accurately answer the question about {breed}?\n"
        'Answer ONLY "YES" or "NO".'
    )

    # ── Agent 3: Answer ───────────────────────────────────────────────────────
    if use_db:
        source_info = f"Knowledge base context:\n{context}"
    else:
        web_text = duckduckgo_search(f"{breed} dog {question}")
        source_info = (
            f"Web search results:\n{web_text}"
            if web_text
            else "Use your general knowledge about dogs."
        )

    final = ask_gemini(
        f"You are a warm, knowledgeable dog breed expert chatting with a dog owner.\n"
        f"Breed: {breed}\n"
        f"Owner's question: {question}\n\n"
        f"{source_info}\n\n"
        "Write a friendly, helpful answer in 2–4 sentences. "
        "Do NOT mention 'the text', 'context', 'search results', or any sources. "
        "Just answer as if you know this naturally."
    )

    return {"response": final}
